version: "3.8"

services:
  data-ingestion-server:
    build: .
    ports:
      - "7860:7860"
    env_file: .env
    environment:
      - QDRANT_HOST=qdrant
      # Add other env vars as needed
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
