services:
  data-ingestion-server:
    build: ./data-ingestion-server
    ports:
      - "7860:7860"
    env_file: ./data-ingestion-server/.env
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant

  nexlify-ai-agentics-server:
    build: ./nexlify-ai-agentics-server
    ports:
      - "8000:8000"
    env_file: ./nexlify-ai-agentics-server/.env
    environment:
      - NEXLIFY_DATA_INGESTION_SERVICE_BASE_URI=http://data-ingestion-server:7860
    depends_on:
      - data-ingestion-server

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
