vector_db_search_task:
  description: >
    Use the NexlyfySearch tool to query the vector database for the given {query}.
    Analyze the results, which will be in a list of maps like [{text: ..., score: ...}].
    Prioritize and select the best results based on the highest scores, providing the latest and most relevant information.
  expected_output: >
    A summarized list of the top results from the vector database, ordered by descending score.
    Include the text and score for each, limited to the top 5 highest-scoring entries.
  agent: vector_db_searcher

internet_search_task:
  description: >
    Perform an internet search for the {query}, focusing on official documentation sites, Stack Overflow, and GitHub issues.
    Gather relevant solutions, discussions, and up-to-date information from these sources.
  expected_output: >
    A bullet-point list of key findings from the internet search, including sources (e.g., URLs) and brief summaries of relevant information.
    Limit to the top 5-7 most useful results.
  agent: internet_searcher

result_analyzer_task:
  description: >
    Analyze and synthesize the results from the vector database search and internet search.
    Combine the information to provide a comprehensive response to the {query}, prioritizing high-score vector DB results and cross-referencing with web findings.
    Format the final output in clean markdown, including sections for key insights, sources, and any recommendations.
  expected_output: >
    A well-structured markdown document with:
    - An introduction summarizing the {query}
    - Sections for vector DB insights (prioritized by score)
    - Sections for web research findings
    - A conclusion with synthesized analysis
    - References to sources
  agent: result_analyzer
