name: Nexlify Data Ingestion Server Docker publish

on:
  push:
    branches: [ "main" ]
    paths: [ "data-ingestion-server/**" ]

env:
  REGISTRY: deepak93p
  IMAGE_NAME: nexlify-data-ingestion-server


jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              env:
                  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PWD: ${{ secrets.DOCKER_PASSWORD }}
              run: echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

            - name: Build and Push Docker Image
              working-directory: data-ingestion-server
              run: |
                docker build --no-cache -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f Dockerfile .
                docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            - name: Clean up Docker system
              run: docker system prune -f